Repository andela/ah-groot-frontend, pull requests merged in 2019-04, with the labels that each got.

#13 #164069274 Social login facebook google
  .codeclimate.yml
  .vscode/launch.json
  package-lock.json
  package.json
  src/actions/SocialAuth/ActionTypes.js
  src/actions/SocialAuth/FacebookActions.js
  src/actions/SocialAuth/GoogleActions.js
  src/components/SocialAuth.js
  src/components/login/LoginForm.js
  src/components/login/LoginModal.js
  src/config.json
  src/containers/SocialAuthContainer.js
  src/containers/urls.js
  src/reducers/SocialAuth/SocialAuthReducers.js
  src/reducers/index.js
  src/styles/landing.scss
  src/styles/loginModal.scss
  tests/SocialAuthor/SocialAuthActions.spec.js
  tests/SocialAuthor/SocialAuthViews.spec.js
  tests/SocialAuthor/SocialauthReducers.spec.js
  tests/SocialAuthor/Socialcomponent.spec.js
  tests/SocialAuthor/__snapshots__/SocialAuthViews.spec.js.snap
  tests/SocialAuthor/__snapshots__/Socialcomponent.spec.js.snap
  tests/landing_page/LandingPage.spec.js
  tests/login/LoginActions.spec.js
  tests/reducers.spec.js
  webpack.config.js
Labels: finished

#35 #164069293 Users should be able to like comments
  src/actions/commentAction.js
  src/actions/types.js
  src/components/comments/Comment.js
  src/components/comments/CommentsPanel.js
  src/containers/Comments/Comment.js
  src/containers/Comments/CommentContainer.js
  src/reducers/commentReducer.js
  src/styles/comments.scss
  src/styles/singlearticle.scss
  tests/comments/commentActions.spec.js
  tests/comments/commentReducers.spec.js
  tests/comments/comments.spec.js
Labels: MERGE READY

#38 #164069290 report an article
  .gitignore
  src/actions/report/reportingActions.js
  src/components/report/Report.js
  src/containers/Articles/SingleArticleView.js
  src/containers/report/ReportingContainer.js
  src/reducers/index.js
  src/reducers/reportingReducer.js
  src/styles/rating.scss
  src/styles/report.scss
  tests/reducers.spec.js
  tests/reporting/Report.spec.js
  tests/reporting/ReportingContainer.spec.js
Labels: MERGE READY, REVIEW READY

#40 #164069279 Pagination support
  src/actions/ArticleAction.js
  src/actions/paginationAction.js
  src/actions/profile/retrieveProfileAction.js
  src/components/profile/UpdateProfile.js
  src/containers/App.js
  src/containers/Articles/ArticleFeed.js
  src/containers/profile/Profile.js
  src/reducers/ArticleReducer.js
  src/reducers/index.js
  tests/Articles/ArticleContainers.spec.js
  tests/Articles/ArticleReducers.spec.js
  tests/Articles/paginationAction.spec.js
  tests/reducers.spec.js
Labels: MERGE READY, REVIEW READY, finished
